# Generated by Django 3.1.5 on 2021-04-01 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleme',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='probleme',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
