# Generated by Django 3.1.5 on 2021-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_etudiant', '0002_auto_20210401_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologie',
            name='libelle',
        ),
        migrations.AddField(
            model_name='technologie',
            name='description',
            field=models.CharField(default='Du lourd', max_length=255),
        ),
        migrations.AddField(
            model_name='technologie',
            name='nom',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
    ]
