# Generated by Django 3.1.5 on 2021-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_etudiant', '0004_auto_20210401_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='reponse',
            field=models.TextField(default='Rien'),
            preserve_default=False,
        ),
    ]
