# Generated by Django 3.1.5 on 2021-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_etudiant', '0006_auto_20210404_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
